import { CategoryLevel1, CategoryLevel2, CategoryLevel3 } from '../../types';

import NoIcon from './activity-icons/NoIcon';
import Cycling from './activity-icons/Cycling';
import Active from './activity-icons/Lightning';
import Football from './activity-icons/Football';
import People from './activity-icons/People';
import Spa from './activity-icons/Spa';
import Stretching from './activity-icons/Spa';
import Dancing from './activity-icons/Dancing';
import Palette from './activity-icons/Palette';
import Scissors from './activity-icons/Scissors';
import Book from './activity-icons/Book';

type CategoryLevel1Icons = Record<CategoryLevel1, React.FC>;
type CategoryLevel2Icons = Record<CategoryLevel2, React.FC>;
type CategoryLevel3Icons = Record<CategoryLevel3, React.FC>;

const categoryLevel1Icons: CategoryLevel1Icons = {
  Active: Active,
  Social: People,
  Creative: Palette,
  Leisure: Spa,
  Educational: Book,
  Other: NoIcon,
};

const categoryLevel2Icons: CategoryLevel2Icons = {
  Acrobatics: Stretching,
  'Air sports': NoIcon,
  Archery: NoIcon,
  'Ball sports': NoIcon,
  'Board games': NoIcon,
  Climbing: NoIcon,
  Cycling: Cycling,
  Combat: NoIcon,
  'Cue sports': NoIcon,
  Dancing: Dancing,
  Dogs: NoIcon,
  Equestrian: NoIcon,
  Fishing: NoIcon,
  'Food and drink': NoIcon,
  Football: Football,
  Gaming: NoIcon,
  Golf: NoIcon,
  Gymnastics: Stretching,
  Yoga: NoIcon,
  'Ice sports': NoIcon,
  'Kite sports': NoIcon,
  Parkour: Stretching,
  'Racquet sports': NoIcon,
  'Remote control': NoIcon,
  Running: NoIcon,
  Sailing: NoIcon,
  'Snow sports': NoIcon,
  Shooting: NoIcon,
  Walking: NoIcon,
  Watersports: NoIcon,
  Weightlifting: NoIcon,
  Motorsport: NoIcon,
  'Model making': NoIcon,
  'Books and reading': Book,
  Sightseeing: NoIcon,
  Gambling: NoIcon,
};

const categoryLevel3Icons: CategoryLevel3Icons = {
  Breakdancing: Dancing,
  Cheerleading: Dancing,
  'Latin dancing': Dancing,
  'Ballroom dancing': Dancing,
  'Salsa dancing': Dancing,
  'Ice skating': NoIcon,
  'Figure skating': NoIcon,
  Freerunning: NoIcon,
  Trampolining: NoIcon,
  Gliding: NoIcon,
  Orienteering: NoIcon,
  'Hang gliding': NoIcon,
  'Model aircraft': NoIcon,
  Skydiving: NoIcon,
  'Wingsuit flying': NoIcon,
  Paragliding: NoIcon,
  'Field archery': NoIcon,
  'Indoor archery': NoIcon,
  'Mounted archery': NoIcon,
  Badminton: NoIcon,
  'Football tennis': Football,
  'Five-a-side football': Football,
  'Table tennis': NoIcon,
  Tennis: NoIcon,
  Volleyball: NoIcon,
  Basketball: NoIcon,
  Netball: NoIcon,
  Baseball: NoIcon,
  Cricket: NoIcon,
  Skateboarding: NoIcon,
  Longboarding: NoIcon,
  Scootering: NoIcon,
  Snowboarding: NoIcon,
  Surfing: NoIcon,
  Bodyboarding: NoIcon,
  Skimboarding: NoIcon,
  Wakesurfing: NoIcon,
  Windsurfing: NoIcon,
  Paddleboarding: NoIcon,
  Dodgeball: NoIcon,
  Frisbee: NoIcon,
  Quidditch: NoIcon,
  Abseiling: NoIcon,
  'Ice climbing': NoIcon,
  Mountaineering: NoIcon,
  'Rock climbing': NoIcon,
  Bouldering: NoIcon,
  Canyoning: NoIcon,
  Coasteering: NoIcon,
  BMX: Cycling,
  'Mountain biking': Cycling,
  Velodrome: Cycling,
  'Road biking': Cycling,
  Unicycling: Cycling,
  Aikido: NoIcon,
  Jujutsu: NoIcon,
  Judo: NoIcon,
  Wrestling: NoIcon,
  Karate: NoIcon,
  Kickboxing: NoIcon,
  'Tai chi': NoIcon,
  Taekwondo: NoIcon,
  Boxing: NoIcon,
  'Muay Thai': NoIcon,
  Fencing: NoIcon,
  Billiards: NoIcon,
  Pool: NoIcon,
  Snooker: NoIcon,
  Dressage: NoIcon,
  'Horse racing': NoIcon,
  Polo: NoIcon,
  Rugby: NoIcon,
  'Driving range': NoIcon,
  'Pitch and putt': NoIcon,
  'Mini golf': NoIcon,
  '18-hole golf': NoIcon,
  'Ice hockey': NoIcon,
  Kitesurfing: NoIcon,
  Parasailing: NoIcon,
  'Kite buggy': NoIcon,
  Triathlon: NoIcon,
  Marathon: NoIcon,
  Squash: NoIcon,
  Drone: NoIcon,
  'RC racing': NoIcon,
  '5K run': NoIcon,
  '10K run': NoIcon,
  'Cross-country run': NoIcon,
  'Half marathon': NoIcon,
  Sprinting: NoIcon,
  Skiing: NoIcon,
  'Clay pigeon shooting': NoIcon,
  'Field shooting': NoIcon,
  'Air rifle shooting': NoIcon,
  Airsoft: NoIcon,
  'Laser tag': NoIcon,
  Paintball: NoIcon,
  Hockey: NoIcon,
  Lacrosse: NoIcon,
  Hurling: NoIcon,
  Canoeing: NoIcon,
  Kayaking: NoIcon,
  Rafting: NoIcon,
  Swimming: NoIcon,
  'Scuba diving': NoIcon,
  Snorkelling: NoIcon,
  Freediving: NoIcon,
  Diving: NoIcon,
  Boating: NoIcon,
  Darts: NoIcon,
  Bridge: NoIcon,
  Poker: NoIcon,
  Quiz: NoIcon,
  Chess: NoIcon,
  'Bunjee jumping': NoIcon,
  Rowing: NoIcon,
  Punting: NoIcon,
  'Wheelchair racing': NoIcon,
  Croquet: NoIcon,
  Boules: NoIcon,
  Bowling: NoIcon,
  'Axe throwing': NoIcon,
  Bingo: NoIcon,
  Baking: NoIcon,
  Cooking: NoIcon,
  Crafting: Scissors,
  Pottery: NoIcon,
  VR: NoIcon,
  'Escape rooms': NoIcon,
  Massage: NoIcon,
  'Painting and drawing': Palette,
  'Cocktail making': NoIcon,
  'Arcade games': NoIcon,
  'Mystery games': NoIcon,
  'Treasure hunts': NoIcon,
  'Food tasting': NoIcon,
  'Wine tasting': NoIcon,
  Rollercoasters: NoIcon,
  'Fun fairs': NoIcon,
  'Go karting': NoIcon,
  Exhibitions: NoIcon,
  'Flower arranging': NoIcon,
  Comedy: NoIcon,
  Pilates: NoIcon,
  Cinema: NoIcon,
  Zoo: NoIcon,
  Bootcamp: NoIcon,
  Softplay: NoIcon,
};

const allCategoryIcons = { ...categoryLevel1Icons, ...categoryLevel2Icons, ...categoryLevel3Icons };

export { categoryLevel1Icons, categoryLevel2Icons, categoryLevel3Icons, allCategoryIcons };
